//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuotantoV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asiakkaanperustiedot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiakkaanperustiedot()
        {
            this.Asiakasluokittelu = new HashSet<Asiakasluokittelu>();
            this.Asiakastapahtumat = new HashSet<Asiakastapahtumat>();
        }

        public int Asiakasnumero { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
        public string Puhelin { get; set; }
        public string Sähköposti { get; set; }
        public string Laskutusnimi { get; set; }
        public string Laskutusosoite { get; set; }
        public string Laskutuspostinumero { get; set; }
        public string Laskutuspostitoimipaikka { get; set; }
        public string Nimi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakasluokittelu> Asiakasluokittelu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //[Display(Name = "Asiakastapahtumat")]
        //[Required(ErrorMessage ="VIRHE")]
        public virtual ICollection<Asiakastapahtumat> Asiakastapahtumat { get; set; }
    }
}
