//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuotantoV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asiakasluokittelu
    {
        public int Luokitteluid { get; set; }
        public int Asiakasnumero { get; set; }
        public bool Eläkeläisalennus { get; set; } = false;
        public bool Tv { get; set; } = false;
        public bool Pöytäkone { get; set; } = false;
        public bool Kannettava { get; set; } = false;
        public bool Matkapuhelin { get; set; } = false;
        public bool Tabletti { get; set; } = false;
        public bool Mokkula { get; set; } = false;
        public bool Wlan { get; set; } = false;

        public virtual Asiakkaanperustiedot Asiakkaanperustiedot { get; set; }
    }
}
