//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuotantoV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tuotantoEntities : DbContext
    {
        public tuotantoEntities()
            : base("name=tuotantoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakasluokittelu> Asiakasluokittelu { get; set; }
        public virtual DbSet<Asiakastapahtumat> Asiakastapahtumat { get; set; }
        public virtual DbSet<Asiakkaanperustiedot> Asiakkaanperustiedot { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
    }
}
